import{R as u,S as f,N as m,P as y,A as g}from"./assets/vendor-0TNtLCYM.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const h="https://paw-hut.b.goit.study/api/feedbacks";document.addEventListener("DOMContentLoaded",()=>{const s=document.getElementById("feedbacks-wrapper"),n=document.getElementById("loader"),i=document.getElementById("toast-container");if(!s||!n||!i)return;const c=a=>{const r=document.createElement("div");r.className="toast-message",r.textContent=a,i.appendChild(r),setTimeout(()=>r.remove(),4e3)},e=a=>{s.innerHTML="",a.forEach(({rate:r,description:o,author:p})=>{const l=document.createElement("div");l.className="swiper-slide",l.innerHTML=`
        <article class="feedback-card">
          <div class="feedback-card__rating">
          <div class="star-rating star-rating--medium" data-score="${r}"></div>
        </div>
          <p class="feedback-card__text">${o}</p>
          <span class="feedback-card__author">${p}</span>
        </article>`,s.appendChild(l)}),document.querySelectorAll(".star-rating").forEach(r=>{new u(r,{readOnly:!0,path:"./img",starHalf:"star-half.png",starOn:"star-filled.png",starOff:"star-outline.png",numberMax:5}).init()})},t=()=>{new f(".success-stories__slider",{modules:[m,y],slidesPerView:1,spaceBetween:24,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0},loop:!1,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:2}}})};(async()=>{n.style.display="block";try{const a=await fetch(h);if(!a.ok)throw new Error("Помилка завантаження відгуків");const o=(await a.json()).feedbacks;if(!o.length||o.length<3)throw new Error("Недостатньо відгуків");e(o),t()}catch(a){c(a.message)}finally{n.style.display="none"}})()});window.addEventListener("load",function(){var s=document.querySelector(".js-preloader");s&&(s.style.transition="opacity 1s ease-in-out",s.style.opacity="0",this.setTimeout(function(){s.style.display="none"},6e3))});new g(".accordion-container",{duration:400,showMultiple:!1,elementClass:"ac",triggerClass:"ac-item-header",panelClass:"ac-panel"});
//# sourceMappingURL=index.js.map
